# Generated by Django 6.0.6 on 2026-06-13 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeteringRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='মিটারিং রানের নাম')),
                ('meter_type', models.CharField(choices=[('Turbine', 'টারবাইন মিটার'), ('Orifice', 'অরিফিস মিটার')], default='Turbine', max_length=10)),
                ('size_inch', models.IntegerField(verbose_name='সাইজ (ইঞ্চি)')),
                ('g_series', models.CharField(blank=True, max_length=20, null=True, verbose_name='জি সিরিজ')),
                ('is_evc', models.BooleanField(default=False, verbose_name='ইভিসি আছে কি না?')),
                ('is_evc_active', models.BooleanField(default=False, verbose_name='ইভিসি কার্যকর কি না?')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='স্টেশনের নাম')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(verbose_name='মাস এবং বছর')),
                ('start_vbt', models.FloatField(default=0.0, verbose_name='শুরুর Vbt')),
                ('start_vmt', models.FloatField(default=0.0, verbose_name='শুরুর Vmt')),
                ('start_mechanical', models.FloatField(default=0.0, verbose_name='শুরুর মেকানিক্যাল ইনডেক্স')),
                ('end_vbt', models.FloatField(default=0.0, verbose_name='শেষের Vbt')),
                ('end_vmt', models.FloatField(default=0.0, verbose_name='শেষের Vmt')),
                ('end_mechanical', models.FloatField(default=0.0, verbose_name='শেষের মেকানিক্যাল ইনডেক্স')),
                ('total_flow', models.FloatField(blank=True, null=True, verbose_name='মোট গ্যাস প্রবাহ')),
                ('metering_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metering.meteringrun')),
            ],
        ),
        migrations.AddField(
            model_name='meteringrun',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metering_runs', to='metering.station'),
        ),
    ]
